language: bash

sudo: required

services:
  - docker

env:
  global:
    - ANSIBLE_VERSION=2.3.0.0

before_script:
  - ssh-keygen -t rsa -P "" -f ansible

script:
  - docker build -t lindeboomio/ansible-test-target-alpine .
  - export AUTHORIZED_KEY=$(cat test/ansible.pub)
  - docker-compose run test

after_script:
  - rm ansible ansible.pub

