language: bash

sudo: required

services:
  - docker

env:
  global:
    - REPOSITORY_NAME=lindeboomio/ansible-test-target-alpine
    - DEFAULT_TAG=development
    - ANSIBLE_VERSION=2.3.0.0

before_script:
  - ssh-keygen -t rsa -P "" -f test/ansible

script:
  - ./build.sh

after_script:
  - rm ansible ansible.pub

