language: bash

sudo: required

services:
  - docker

env:
  global:
    - ANSIBLE_VERSION=2.3.0.0
    - AUTHORIZED_KEY=ansible.pub

before_script:
  - ssh-keygen -t rsa -P "" -f ansible

script:
  - docker build -t lindeboomio/ansible-test-target-alpine .
  - docker-compose run test

